name: Deploy myProject to host
'on':
 push:
   branches:
     - master

jobs: 
 docker:
   runs-on: ubuntu-latest
   steps:
     -
       name: Checkout
       uses: actions/checkout@v4
     -
       name: Set up QEMU
       uses: docker/setup-qemu-action/@v3
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     -
       name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
     -
       name: prepare the docker-compose run
       run: |
             ls -l
     -
       name: Build and push
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: phonemyat52/234-deploylab-lab11_project:latest
     -
       name: copy file via ssh password
       uses: appleboy/scp-action@v0.1.7
       with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.HOST_USER_NAME }}
        key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
        port: 22
        source: "docker-compose.yml"
        target: "/home/ubuntu/lab_11"
     -
       name: docker compose
       uses: appleboy/ssh-action@v1.2.1
       with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.HOST_USER_NAME }}
        key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/lab_11
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username
          ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker compose down
          docker compose pull
          docker compose up -d
          rm -rf /home/ubuntu/lab_11


           
